objects/TASKRAY__Project__c.object
<CustomObject>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>TaskRay Projects (Account)</relationshipLabel>
        <relationshipName>TaskRay_Projects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TASKRAY__Project_Task__c.object
<CustomObject>
    <description>This is the primary TaskRay object for tasks.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <fields>
        <fullName>TASKRAY__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TaskRay Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time__c.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>Timesheet__c</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>Time-{0}</displayFormat>
        <label>Time Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Taskray_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Taskray Task</label>
        <referenceTo>TASKRAY__Project_Task__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TimeToTaskRayTimeTest.cls
@isTest(seeAllData=false)
public class TimeToTaskRayTimeTest {
    
    public static testMethod void testTaskTime(){ 
		//Account
		Account acc = new Account();
        acc.Name = 'Test account';
        insert acc;
        
        //New TaskRay Project
        TASKRAY__Project__c project = new TASKRAY__Project__c();
        project.Account__c = acc.Id;
        project.Name = 'Test Project';
		insert project;
        
        //New TaskRay Task
        TASKRAY__Project_Task__c task = new TASKRAY__Project_Task__c();
        task.Name = 'Test Task';
        task.TASKRAY__Project__c = project.Id;
        insert task;
        
        //new Timesheet
		Timesheet__c timesheet = new Timesheet__c();
        timesheet.Taskray_Task__c = task.Id;
        insert timesheet;

        Time__c testTime = new Time__c();
        testTime.Timesheet__c = timesheet.Id;
        testTime.Start_Time__c = DateTime.now();
        testTime.End_Time__c = DateTime.now();
        insert testTime;
        
        
    } 
}